In [1]:
import torch

In [2]:
ht=torch.tensor([1.67,1.77,1.89,1.56,1.89,1.78],dtype=torch.float32)
wt=torch.tensor([77,68,98,54,65,90],dtype=torch.float32)

bmi=torch.tensor([27.60,21.70,27.43,22.18,18.19,28.40],dtype=torch.float32)


In [3]:
w=torch.tensor(1.0,requires_grad=True)

def forward(wt,ht):
    return (w*wt/(ht)**2)

def loss(y_pred,y):
    return ((y_pred-y)**2).mean()


In [4]:
learning_rate=0.01
n_iters=20

In [5]:
for epoch in range(n_iters):
    y_pred=forward(wt,ht)
    print(y_pred)

    l=loss(y_pred,bmi)

    l.backward()

    with torch.no_grad():
        w+=learning_rate* w.grad
    
    w.grad.zero_()

    if(epoch%2==0):
        print(f"epoch no: {epoch} ,loss= {l:.3},w={w:.3}")
print(bmi)
print(y_pred)

tensor([27.6095, 21.7051, 27.4348, 22.1894, 18.1966, 28.4055],
       grad_fn=<DivBackward0>)
epoch no: 0 ,loss= 5e-05,w=1.0
tensor([27.7005, 21.7767, 27.5253, 22.2625, 18.2566, 28.4991],
       grad_fn=<DivBackward0>)
tensor([28.8884, 22.7106, 28.7058, 23.2173, 19.0395, 29.7214],
       grad_fn=<DivBackward0>)
epoch no: 2 ,loss= 1.31,w=1.61
tensor([44.3974, 34.9030, 44.1166, 35.6816, 29.2610, 45.6775],
       grad_fn=<DivBackward0>)
tensor([246.8628, 194.0708, 245.3016, 198.4004, 162.7000, 253.9805],
       grad_fn=<DivBackward0>)
epoch no: 4 ,loss= 3.8e+04,w=1.05e+02
tensor([2889.9951, 2271.9653, 2871.7180, 2322.6509, 1904.7109, 2973.3213],
       grad_fn=<DivBackward0>)
tensor([37395.3906, 29398.3281, 37158.8906, 30054.1797, 24646.2031, 38473.5977],
       grad_fn=<DivBackward0>)
epoch no: 6 ,loss= 1.1e+09,w=1.77e+04
tensor([487854.2500, 383525.8438, 484768.9062, 392082.0000, 321530.4062,
        501920.3750], grad_fn=<DivBackward0>)
tensor([6368475.5000, 5006567.0000, 6328199.0000,