In [1]:
import torch


In [3]:
x=torch.tensor([1,2,3,4],dtype=torch.float32)
y=torch.tensor([2,4,6,8],dtype=torch.float32)

w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

In [4]:
def forward(x):
    return w*x

def loss(y,y_pred):
    return ((y_pred-y)**2).mean()

In [5]:
learning_rate=0.01
n_iters=100

In [8]:
for epoch in range(n_iters):
    y_pred=forward(x)
    l=loss(y,y_pred)
    l.backward()

    with torch.no_grad():
        w-= learning_rate * w.grad

    # Zero the gradient:
    w.grad.zero_()

    if(epoch%2==0):
        print(f"epoch no: {epoch} ,loss= {l:.3},w={w:.3}")
print(y_pred)

tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
epoch no: 0 ,loss= 8.99e-13,w=2.0
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
epoch no: 2 ,loss= 8.99e-13,w=2.0
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
epoch no: 4 ,loss= 8.99e-13,w=2.0
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
epoch no: 6 ,loss= 8.99e-13,w=2.0
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
epoch no: 8 ,loss= 8.99e-13,w=2.0
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
epoch no: 10 ,loss= 8.99e-13,w=2.0
tensor([2.0000, 4.0000, 6.0000, 8.0000], grad_fn=<MulBackward0>)
tensor([2.0000,